Prevented the special PKGBUILDs from being executed normally. Fixed mhpkg clean_all.

diff --git a/mhserv/PKGBUILD b/mhserv/PKGBUILD
--- a/mhserv/PKGBUILD
+++ b/mhserv/PKGBUILD
@@ -1,3 +1,7 @@
+if [ -z "$MH_PKG_PATH" ]; then
+    echo "Cannot be built normally using makepkg, use 'mhpkg install' instead."
+    exit 1
+fi
 source "$MH_PKG_PATH/lib/package.sh"
 setup_git "github.com" "mihail-8480"
 setup_package "mhserv" "A relatively simple multi-platform C HTTP server."
