Added "lib" command to mhpkg.

diff --git a/mhpkg b/mhpkg
--- a/mhpkg
+++ b/mhpkg
@@ -1,6 +1,6 @@
 #!/bin/sh
 clean() {
-  for d in */ ; do
+  for d in */; do
     if [ "$d" = "lib/" ]; then
       continue
     fi
@@ -11,19 +11,19 @@ clean() {
 }
 
 install() {
-  cd "$1" || exit 1
+  cd "${1}" || exit 1
   makepkg -si
   cd ..
 }
 
 build() {
-  cd "$1" || exit 1
+  cd "${1}" || exit 1
   makepkg -f
   cd ..
 }
 
 install_all() {
-  for d in */ ; do
+  for d in */; do
     if [ "$d" = "lib/" ]; then
       continue
     fi
@@ -32,7 +32,7 @@ install_all() {
 }
 
 build_all() {
-  for d in */ ; do
+  for d in */; do
     if [ "$d" = "lib/" ]; then
       continue
     fi
@@ -49,41 +49,47 @@ help() {
   echo "- clean: Cleans all downloaded and generated files."
   echo "- install_all: Builds and installs every package."
   echo "- build_all: Builds every package."
+  echo "- lib: Don't do anything (declares the functions)."
   echo
 }
 
+main() {
+  if [ "${1}" = "clean" ]; then
+    clean
+    exit 0
+  fi
 
-if [ "$1" = "clean" ]; then
-  clean
-  exit 0
+  if [ "${1}" = "install_all" ]; then
+    install_all
+    exit 0
+  fi
+
+  if [ "${1}" = "build_all" ]; then
+    build_all
+    exit 0
+  fi
+
+  if [ "${1}" = "install" ]; then
+    install "${2}"
+    exit 0
+  fi
+
+  if [ "${1}" = "build" ]; then
+    build "${2}"
+    exit 0
+  fi
+
+  if [ "${1}" = "help" ]; then
+    help
+    exit 0
+  fi
+
+  echo "${0}: missing command."
+  echo "Try '${0} help' for more information."
+  exit 1
+}
+
+
+if [ "${1}" != "lib" ]; then
+  main $@
 fi
-
-if [ "$1" = "install_all" ]; then
-  install_all
-  exit 0
-fi
-
-if [ "$1" = "build_all" ]; then
-  build_all
-  exit 0
-fi
-
-if [ "$1" = "install" ]; then
-  install "$2"
-  exit 0
-fi
-
-if [ "$1" = "build" ]; then
-  build "$2"
-  exit 0
-fi
-
-if [ "$1" = "help" ]; then
-  help
-  exit 0
-fi
-
-
-echo "${0}: missing command."
-echo "Try '${0} help' for more information."
-exit 1
